program validate_emulator
  !
  ! Validate FTorch emulator against Python reference outputs
  !
  ! This program loads test data generated by evaluate_model_debug.py,
  ! runs the emulator on the input features, and compares the results
  ! with the expected Python outputs.
  !
  ! Files expected in current directory (or specify path):
  !   - fortran_test_inputs.txt   : Input features
  !   - fortran_test_outputs.txt  : Expected outputs from Python
  !   - fortran_test_info.txt     : Metadata (optional, for reference)
  !
  use iso_fortran_env, only : real32, real64
  use ftorch, only : torch_model, torch_tensor, torch_tensor_from_array, &
                     torch_model_load, torch_model_forward, torch_delete, &
                     torch_kCPU
  implicit none

  ! Configuration - adjust these based on your model
  integer, parameter :: NUM_FEATURES = 11  ! Number of input features
  integer, parameter :: NUM_OUTPUTS = 4    ! Number of output values (qrtend, nctend, nrtend, qctend)
  character(len=256) :: model_path
  character(len=256) :: data_dir
  
  ! FTorch objects
  type(torch_model) :: emulator
  type(torch_tensor), dimension(1) :: input_tensors
  type(torch_tensor), dimension(1) :: output_tensors

  ! Data arrays
  real(real32), allocatable, target :: features(:,:)
  real(real32), allocatable, target :: tendencies(:,:)
  real(real32), allocatable :: expected_outputs(:,:)
  
  ! Working variables
  integer :: num_samples, num_feat_file, num_out_file
  integer :: i, j, unit_in, unit_out, ios
  character(len=512) :: line
  real(real64) :: max_error, mean_error, error, total_error
  real(real32) :: tolerance
  logical :: all_passed

  ! Default paths (can be overridden via command line)
  model_path = 'emulator_for_e3sm.pt'
  data_dir = '.'
  tolerance = 1.0e-5

  ! Parse command line arguments if provided
  if (command_argument_count() >= 1) then
    call get_command_argument(1, model_path)
  end if
  if (command_argument_count() >= 2) then
    call get_command_argument(2, data_dir)
  end if

  write(*,*) '=================================================='
  write(*,*) 'FTorch Emulator Validation'
  write(*,*) '=================================================='
  write(*,*) 'Model path: ', trim(model_path)
  write(*,*) 'Data directory: ', trim(data_dir)
  write(*,*) ''

  ! Read input features from text file
  write(*,*) 'Loading input features...'
  open(newunit=unit_in, file=trim(data_dir)//'/fortran_test_inputs.txt', &
       status='old', action='read', iostat=ios)
  if (ios /= 0) then
    write(*,*) 'ERROR: Could not open fortran_test_inputs.txt'
    stop 1
  end if
  
  ! Read header line (comment with dimensions)
  read(unit_in, '(A)') line
  read(line(2:), *) num_samples, num_feat_file
  write(*,*) '  Samples:', num_samples, ' Features:', num_feat_file
  
  if (num_feat_file /= NUM_FEATURES) then
    write(*,*) 'WARNING: Expected', NUM_FEATURES, 'features, got', num_feat_file
  end if
  
  allocate(features(1, num_feat_file))
  allocate(tendencies(1, NUM_OUTPUTS))
  allocate(expected_outputs(num_samples, NUM_OUTPUTS))
  
  ! Read expected outputs from Python
  write(*,*) 'Loading expected outputs...'
  open(newunit=unit_out, file=trim(data_dir)//'/fortran_test_outputs.txt', &
       status='old', action='read', iostat=ios)
  if (ios /= 0) then
    write(*,*) 'ERROR: Could not open fortran_test_outputs.txt'
    stop 1
  end if
  
  read(unit_out, '(A)') line  ! Skip header
  do i = 1, num_samples
    read(unit_out, *) (expected_outputs(i, j), j = 1, NUM_OUTPUTS)
  end do
  close(unit_out)
  
  ! Load the TorchScript model
  write(*,*) 'Loading TorchScript model...'
  call torch_model_load(emulator, trim(model_path), torch_kCPU)
  write(*,*) '  Model loaded successfully'
  write(*,*) ''
  
  ! Process each sample
  write(*,*) '=================================================='
  write(*,*) 'Running validation on', num_samples, 'samples'
  write(*,*) '=================================================='
  
  max_error = 0.0d0
  total_error = 0.0d0
  all_passed = .true.
  
  ! Reset file position to read samples
  rewind(unit_in)
  read(unit_in, '(A)') line  ! Skip header again
  
  do i = 1, num_samples
    ! Read input features for this sample
    read(unit_in, *) (features(1, j), j = 1, num_feat_file)
    tendencies = 0.0_real32
    
    ! Create tensors and run inference
    call torch_tensor_from_array(input_tensors(1), features, torch_kCPU)
    call torch_tensor_from_array(output_tensors(1), tendencies, torch_kCPU)
    call torch_model_forward(emulator, input_tensors, output_tensors)
    
    ! Compare outputs
    write(*,*) ''
    write(*,'(A,I3,A)') ' Sample ', i, ':'
    write(*,*) '  Input features:'
    write(*,'(5(E15.8,1X))') (features(1, j), j = 1, min(5, num_feat_file))
    if (num_feat_file > 5) write(*,*) '  ...'
    
    write(*,*) '  Fortran output vs Python expected:'
    do j = 1, NUM_OUTPUTS
      error = abs(dble(tendencies(1, j)) - dble(expected_outputs(i, j)))
      total_error = total_error + error
      if (error > max_error) max_error = error
      
      if (error > tolerance) then
        write(*,'(A,I1,A,E15.8,A,E15.8,A,E10.3,A)') &
          '    output[', j-1, ']: ', tendencies(1, j), &
          ' vs ', expected_outputs(i, j), &
          ' (err=', error, ') MISMATCH!'
        all_passed = .false.
      else
        write(*,'(A,I1,A,E15.8,A,E15.8,A,E10.3,A)') &
          '    output[', j-1, ']: ', tendencies(1, j), &
          ' vs ', expected_outputs(i, j), &
          ' (err=', error, ') OK'
      end if
    end do
    
    ! Cleanup tensors for this iteration
    call torch_delete(output_tensors)
    call torch_delete(input_tensors)
  end do
  
  close(unit_in)
  
  ! Summary
  mean_error = total_error / (num_samples * NUM_OUTPUTS)
  write(*,*) ''
  write(*,*) '=================================================='
  write(*,*) 'Validation Summary'
  write(*,*) '=================================================='
  write(*,'(A,E15.8)') ' Maximum absolute error: ', max_error
  write(*,'(A,E15.8)') ' Mean absolute error:    ', mean_error
  write(*,'(A,E15.8)') ' Tolerance:              ', tolerance
  write(*,*) ''
  
  if (all_passed) then
    write(*,*) '✓ All samples PASSED validation!'
  else
    write(*,*) '✗ Some samples FAILED validation!'
  end if
  
  ! Cleanup
  call torch_delete(emulator)
  deallocate(features, tendencies, expected_outputs)

end program validate_emulator

